### ISSUE TITLE
'PatchEmbed' object has no attribute 'grid_size'

### ISSUE THREAD

**Issue by yangyangshuyang** [nttcslab/msm-mae#4]
Hello,this is an excellent job, but I encountered a problem while studying it. 
After configuring the environment according to the readme file, I ran the code in the quick example and visualization example, but the model failed to load，reporting an error--'PatchEmbed' object has no attribute 'grid_size'.
I don't know if I did something wrong or if there were some issues with the version. I wonder if you have seen this issue before.
Could you please help me with this issue?
![Honeyview_Quicker_20230323_210259](https://user-images.githubusercontent.com/80260875/227213352-c6b362dd-bf04-4f64-857b-2b010c3ab9a4.jpg)
![Honeyview_Quicker_20230323_210236](https://user-images.githubusercontent.com/80260875/227213323-ed00b419-fce4-40a8-bd53-74f8c84bace1.jpg)

**Comment by daisukelab** [comment]
Hi @yangyangshuyang, thank you for your interest!
As far as I rerun the notebook, I found no problem. I guess it would be caused by the mismatch of the timm version.
The MSM-MAE is implemented to use the timm.
https://github.com/nttcslab/msm-mae/blob/main/msm_mae/patch_msm_mae.diff#L8

Mine is 0.5.4, then please check yours.
Thanks for your cooperation!
