### ISSUE TITLE
Why haven't you guys published the HEAR results?

### ISSUE THREAD

**Issue by RicherMans** [nttcslab/msm-mae#6]
Hey @daisukelab ,
Thanks for the great work! 

I was just curious since you already published the paper and your results are openly available, why haven't you put these results into the official HEAR leaderboard such that everybody can see them? 
The results are great btw :).

Regards,
Heinrich

**Comment by daisukelab** [comment]
Hi @RicherMans ,

First, congrats on very nice achievements in your new paper!
https://arxiv.org/abs/2308.11957
I'm wondering what comes next for what we could play with the AudioSet task.

The reason I have not posted our results on the leaderboard is because I don't know if it is still active.
Also, we released the improved version of MSM-MAE last year; we have already moved on to the next research.

I'll try my best for it. (Having many todos...)
Best regards,
Daisuke

**Comment by RicherMans** [comment]
Hey @daisukelab 
thanks a lot for the quick reply!

> First, congrats on very nice achievements in your new paper! 

Thanks, for that!

> The reason I have not posted our results on the leaderboard is because I don't know if it is still active.

I think it is still active, but its not a "open platform" where you can add your scores. You need to provide the results to the official github repo.
After the HEAR challenge I think only Florian (https://github.com/fschmid56/EfficientAT) submitted additional results.

> Also, we released the improved version of MSM-MAE last year; we have already moved on to the next research.

True, its not a must-have of course but I think it might helps to improve the impact of your research overall if people can find the results on some cool leaderboard platforms :).

> I'll try my best for it. (Having many todos...)

yeah, no worries here, I'll close the issue, first things first 👯 .

Thanks a lot, Daisuke!

Kind regards,
Heinrich
